language: bash
services: docker

env:
  - VERSION=14.04.4

before_script:
  - env | sort
  - cd "$VERSION"
  - image="aggr/ubuntu:$VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images
